artifacts_root: artifacts

data_ingestion:
  root_dir: "artifacts/data_ingestion"
  source_URL: "mohamedgobara/26-class-object-detection-dataset"
  local_data_dir: "artifacts/data_ingestion/data"
  unzip_dir: "artifacts/data_ingestion"

prepare_base_model:
  root_dir: "artifacts/prepare_base_model"
  model_name: "yolo11s"
  model_dir: "artifacts/prepare_base_model/model"
  checkpoint_dir: "artifacts/prepare_base_model/checkpoint"

model_training:
  root_dir: "artifacts/model_training"
  model_path: "artifacts/prepare_base_model/model/yolo11s.pt"
  model_coco_datasets: "artifacts/model_training/data/coco"
  model_coco_images: "artifacts/model_training/data/coco/images"
  model_coco_labels: "artifacts/model_training/data/coco/labels"
  output_dir: "artifacts/model_training/output"
  test_path: "artifacts/data_ingestion/data/Senior-Design-VIAD-4/test"
  train_path: "artifacts/data_ingestion/data/Senior-Design-VIAD-4/train"
  valid_path: "artifacts/data_ingestion/data/Senior-Design-VIAD-4/valid"
